apiVersion: v1
kind: Pod
metadata:
  name: time
spec:
  containers:
    - name: time
      image: agrimmer/demo:time
      ports:
        - name: web
          containerPort: 8888
          protocol: TCP