apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: fibonacci-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: fibonacci
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 10m
          memory: 50Mi
        maxAllowed:
          cpu: 50m
          memory: 500Mi
        controlledResources: ["cpu", "memory"]